
GET https://localhost:3000/users


GET https://localhost:3000/users/67cc6731fdeb6f708e656e38


POST https://localhost:3000/users HTTP/1.1
content-Type: application/json

{ "_id": "67cc6731fdeb6f708e656e38",
    "email": "test@example.com",
    "username": "test@test.com",
    "name": "Hello1",
    "ipaddress": "94.121.163.63"
  }


PUT https://localhost:3000/users/67cc6731fdeb6f708e656e38  HTTP/1.1
content-type: application/json

{
    "email": "test@example.com",
    "username": "test@test.com",
    "name": "Hello1",
    "ipaddress": "94.121.163.63"
}

DELETE  https://localhost:3000/users/67cc6731fdeb6f708e656e38 HTTP/1.1